CONNECTALDIR?=../..
S2H_INTERFACES = CoreRequest:F2H.request
H2S_INTERFACES = F2H:CoreIndication

BSVFILES = F2H.bsv
CPPFILES= glue.cpp

CONNECTALFLAGS += -D TRACE_PORTAL

include $(CONNECTALDIR)/Makefile.connectal
